### ISSUE TITLE
Create CI for deployment

### ISSUE THREAD

**Issue by ivanms1** [Free-Code-Camp-Seoul/fcc-seoul-website#27]
As of now, deployment is done manually, we can automate it with github actions.

https://fly.io/docs/app-guides/continuous-deployment-with-github-actions/

**Comment by GMSoudersJr** [comment]
Manual deployment sounds horrible.
Sorry for putting you through that with all those pull requests. Haha!

Let's get this started!

I guess I will need to make a fly.io account, first?

**Comment by GMSoudersJr** [comment]
I went through the tutorial in the link and got their project working. It does not seem too difficult to implement here.

Is there a FLY_API_TOKEN set already? There needs to be one in order to configure the `.github/workflows/fly.yml` file. I can make it the file, but it will not work if that api token is not present

![image](https://github.com/user-attachments/assets/f4ee73e4-7a89-43bf-8a48-d642a79b09ee)

**Comment by ivanms1** [comment]
Added the token!
<img width="1228" alt="Screenshot 2024-07-13 at 8 30 22 AM" src="https://github.com/user-attachments/assets/0b32e749-b870-4dd4-b59b-cea47221a168">

**Comment by GMSoudersJr** [comment]
A quick question before I proceed:

Since `Dockerfile `and `fly.toml` already exist, do I still need to follow steps 3 and 4 from the tutorial?
> 3. Run `fly launch --no-deploy` from within the project source directory to create a new app and a `fly.toml` configuration file.
> 4. Type `y` to when prompted to tweak settings and enter a name for the app. Adjust other settings, such as region, as needed. Then click Confirm Settings.

After copying that here, I noticed that region gets set, so maybe I should.

**Comment by GMSoudersJr** [comment]
So I ran `fly launch --no-deploy` and the first question is:
> `? Would you like to copy its configuration to the new app? (y/N)`
No is the default answer

I chose `No` it changed the organization to `Gerald`. Well here is what it looks like:
![image](https://github.com/user-attachments/assets/a96fc237-c555-436c-ab54-3ead254269f3)

It seems like it would be attached to my account if I proceed with this. Am I wrong?

**Comment by ivanms1** [comment]
I think you only need to add the `.github/workflows/fly.yml` file

**Comment by GMSoudersJr** [comment]
~okay, I'll delete my local branch and start over.~
I cleared the changes and deleted the website from my fly.io account that was created with `fly launch --no-deploy`. That should work, right?!

By the way, I also saw [this](https://fly.io/docs/blueprints/review-apps-guide/) as I looked through the docs. We can have previews built of future PRs!

Would that be doing too much? Haha

**Comment by ivanms1** [comment]
the previews look cool, I am just concerned about the costs.
For now let's do the deployment.
