### ISSUE TITLE
Image on Events page overflows

### ISSUE THREAD

**Issue by Tobio89** [Free-Code-Camp-Seoul/fcc-seoul-website#29]
![image](https://user-images.githubusercontent.com/44494591/204950610-73f373f9-4f44-48de-8b59-7685ce256b29.png)
On mobile, the image on the events page overflows.

**Comment by drecali** [comment]
@Tobio89 thanks for creating this issue and not fixing it directly. I'll try to assign it to someone at the meet-up so they can practice contributing 🙂
