### ISSUE TITLE
Add localization

### ISSUE THREAD

**Issue by ivanms1** [Free-Code-Camp-Seoul/fcc-seoul-website#30]
Support for Korean and English versions of the site.
https://github.com/i18next/next-i18next

**Comment by GMSoudersJr** [comment]
I was wrong earlier about this i18 warning going away. It is still there.
> react-i18next:: You will need to pass in an i18next instance by using initReactI18next

Going to take a stab at this today.

**Comment by GMSoudersJr** [comment]
@ivanms1, Do we only need translations at this point or further integration with TypeScript?

**Comment by ivanms1** [comment]
translations are more important

**Comment by ivanms1** [comment]
if you start working on that a little FYI, you gotta restart the app for it to pickup the translations

**Comment by GMSoudersJr** [comment]
I might have to bow out from this one. My Korean is horrible. Haha. There should be someone willing to take up the cause.
