### ISSUE TITLE
Font issue

### ISSUE THREAD

**Issue by GMSoudersJr** [Free-Code-Camp-Seoul/fcc-seoul-website#47]
Noticed a difference between the fonts for the production site and my local version. Opened Chrome Dev Tools and saw this: 
![fCC Seoul font issue](https://github.com/Free-Code-Camp-Seoul/fcc-seoul-website/assets/44438849/25aadc9d-de02-419f-a732-afc3c3bde3e8)

@ivanms1 suggested [this as a fix](https://nextjs.org/docs/pages/building-your-application/optimizing/fonts).

Going to get started on it.

**Comment by GMSoudersJr** [comment]
I started working on the issue before I saw the assignment. I made a PR already and think I messed up the flow / history.

**Comment by ivanms1** [comment]
@GMSoudersJr yeah I merged your PR so your fork is probably not up to date.
Let me add you as a collaborator so you can work directly from the repo (no fork needed)

**Comment by GMSoudersJr** [comment]
@ivanms1, Thanks.

I'll wait for a comment on my latest PR before I make more updates.

**Comment by ivanms1** [comment]
I understand the problem now, I commented.

**Comment by GMSoudersJr** [comment]
I am glad you do because GitHub ties my brain in knots after a while. I am glad to be getting some practice so it does not seem so foreign anymore.
