### ISSUE TITLE
Change favicon

### ISSUE THREAD

**Issue by ivanms1** [Free-Code-Camp-Seoul/fcc-seoul-website#53]
Replace Vercel favicon with a FCC favicon

**Comment by ivanms1** [comment]
@GMSoudersJr if you want to, you can tackle this one.

**Comment by GMSoudersJr** [comment]
the same dark one fCC uses on their site?

**Comment by ivanms1** [comment]
that's what I was thinking but I talked to @drecali just now and he says we have our own, I'll try to find it.

**Comment by GMSoudersJr** [comment]
@drecali, any idea where this favicon could be?

**Comment by drecali** [comment]
@GMSoudersJr unfortunately I don't have a favicon but I do have this SVG. Not sure if the GitHub upload will work properly. If not, I can DM you.
![FCCSeoulf](https://github.com/user-attachments/assets/143cd46c-fb06-4dbd-bd7a-d1bea9a113a5)

**Comment by GMSoudersJr** [comment]
I'm sure Next.js can figure it out. Thanks

**Comment by GMSoudersJr** [comment]
I guess I was too optimistic about what Next could do.

It complains that it is not a valid image file. The image may be corrupted or an unsupported format.

Never mind. Got it to display, need to resize it now

**Comment by GMSoudersJr** [comment]
I downloaded the file you sent on Discord, copied it to my local branch, then changed the name to icon.svg in the app directory according to Next.js documentation.

**Comment by GMSoudersJr** [comment]
I think I figured something out.

**Comment by GMSoudersJr** [comment]
Version 1: white background
![image](https://github.com/user-attachments/assets/6b8db26e-0b2c-4603-864f-6deb2696fe5c)

Version 2: transparent background
![image](https://github.com/user-attachments/assets/8fe19b62-d0d1-4608-9802-77772674db6e)

Version 3: rounded border with white background
![image](https://github.com/user-attachments/assets/11ea484f-844c-438a-8e2b-7b301fc9fffa)

**Comment by drecali** [comment]
@GMSoudersJr well done! I like Version 3 the most but the others are good too. What do you think @ivanms1?

**Comment by ivanms1** [comment]
yeah I like option 3 as well!
