### ISSUE TITLE
migrate to app router

### ISSUE THREAD

**Issue by ivanms1** [Free-Code-Camp-Seoul/fcc-seoul-website#61]

**Comment by GMSoudersJr** [comment]
Reading through the docs now. :sweat:

**Comment by ivanms1** [comment]
yeah the app is not that big so I imagine it won't be too hard, but who knows 😆

**Comment by GMSoudersJr** [comment]
Thankfully it is not that big. I was just getting my mind around the structure and now it's going to change. :rofl:
