### ISSUE TITLE
Dependabot PRs

### ISSUE THREAD

**Issue by ivanms1** [Free-Code-Camp-Seoul/fcc-seoul-website#65]
Go through dependabbot PRs

- Test and make sure everything still works (yarn dev, yarn build, etc)
- if everything is ok merge PR

**Comment by GMSoudersJr** [comment]
Worked through the dependabot PRs

- ran `yarn dev` and tested the navigation along with i18n / localization
- ran `yarn build` and all were successful
- merged the PRs
